---

- name: Create maintenance folder.
  ansible.builtin.file:
    path: "/home/{{ username }}/maintenance/logs"
    state: directory
    owner: "{{ username }}"
    group: "{{ unixgroup }}"
    mode: "0755"

- name: Copy maintenance script.
  ansible.builtin.copy:
    src: "mpserver-maintenance.sh"
    dest: "/home/{{ username }}/maintenance/mpserver-maintenance.sh"
    owner: "{{ username }}"
    group: "{{ unixgroup }}"
    mode: '744'

- name: Replace username, compose_dir and dockerdata_dir in maintenance script.
  ansible.builtin.lineinfile:
    dest: "/home/{{ username }}/maintenance/mpserver-maintenance.sh"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "present"
  with_items:
    - regexp: "^DOCKER_USER="
      line: "DOCKER_USER={{ username }}"
    - regexp: "^COMPOSE_REPO="
      line: "COMPOSE_REPO=\"{{ docker_compose_dir }}\""
    - regexp: "^DOCKERDATA="
      line: "DOCKERDATA=\"{{ docker_data_dir }}\""

- name: Copy systemd service for maintenance script.
  become: true
  ansible.builtin.template:
    src: "mpserver-maintenance.service.j2"
    dest: "/etc/systemd/system/mpserver-maintenance.service"
    owner: root
    group: root
    mode: '0644'

- name: Setup systemd service for maintenance script.
  become: true
  ansible.builtin.systemd:
    name: mpserver-maintenance
    state: "started"
    enabled: false

- name: Copy btrbk configuration.
  ansible.builtin.copy:
    src: "btrbk.conf"
    dest: "/etc/btrbk/btrbk.conf"
    owner: root
    group: root
    mode: '0644'
