---

- name: Create maintenance folder.
  ansible.builtin.file:
    path: "/home/{{ username }}/maintenance/logs"
    state: directory
    owner: "{{ username }}"
    group: "{{ unixgroup }}"
    mode: "0755"

- name: Copy maintenance script.
  ansible.builtin.template:
    src: "mpserver-maintenance.sh.j2"
    dest: "/home/{{ username }}/maintenance/mpserver-maintenance.sh"
    owner: "{{ username }}"
    group: "{{ unixgroup }}"
    mode: '744'
  tags: script

- name: Copy btrbk configuration.
  ansible.builtin.template:
    src: "btrbk.conf.j2"
    dest: "{{ btrbk_config_dir }}"
    owner: root
    group: root
    mode: '0644'

- name: Copy systemd service for maintenance script.
  become: true
  ansible.builtin.template:
    src: "mpserver-maintenance.service.j2"
    dest: "/etc/systemd/system/mpserver-maintenance.service"
    owner: root
    group: root
    mode: '0644'

- name: Enable systemd service for maintenance script.
  become: true
  ansible.builtin.systemd:
    name: mpserver-maintenance
    state: "stopped"  # does not have to be started and enabled since it's triggered by the timer
    enabled: false

- name: Copy systemd timer which triggers systemd service.
  become: true
  ansible.builtin.copy:
    src: "mpserver-maintenance.timer"
    dest: "/etc/systemd/system/mpserver-maintenance.timer"
    owner: root
    group: root
    mode: '0644'

- name: Enable systemd timer for service trigger.
  become: true
  ansible.builtin.systemd:
    name: mpserver-maintenance.timer
    state: "started"
    enabled: true
