---

- name: Tasks and roles for all hosts
  hosts: mpserver
  vars_files:
    - vars/vault.yml

  roles:
    - role: system
      become: true
      tags:
        - system

    - role: containers
      become: false
      tags:
        - compose

    - role: maintenance
      become: true
      tags:
        - maintenance
